Plaboo/Controllers/AlternativesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Plaboo.Context;
using Plaboo.Models;

namespace Plaboo.Controllers
{
    [RequireHttps]
    public class AlternativesController : Controller
    {
        private PlabooContext db = new PlabooContext();

        // GET: This is a get method to get all details of the plastic items in the database
        public ActionResult Index()
        {
            return View(db.Plastics.ToList());  //return all plastics to the model
        }


       //to dispose off
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Plaboo/Controllers/RecyclingCentresController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Plaboo.Context;
using Plaboo.Models;

namespace Plaboo.Controllers
{
    public class RecyclingCentresController : Controller
    {
        private PlabooContext db = new PlabooContext();   //db context instance

        //GET: RecyclingCentres
        //This will return all distinct suburbs of the recycling centers to shpw it to the users using mapbox
        public ActionResult Index()
        {
            ViewBag.availabletags = db.RecyclingCentres.Select(x => x.Postcode).Distinct().ToList().ToArray(); //used LINQ to select the distinct
            //suburbs from the database and pass it to the view to show them
            return View(db.RecyclingCentres.ToList()); //return the model to the view

        }

        //action for suburb autocomplete
        public List<string> AutoComplete()
        {
            return db.RecyclingCentres.Select(x => x.Postcode).ToList();  //return all suburbs for jquery autocomplete

        }

        //action to return the recycling centers of the searched suburb
        [HttpPost]
        public ActionResult Index(FormCollection formcollection)
        {
            var postcodestring = formcollection["postcode"];  //suburb as a string from the formcollection variable
            ViewBag.availabletags = db.RecyclingCentres.Select(x => x.Postcode).Distinct().ToList().ToArray();  //used LINQ to select the distinct
            //suburbs from the database and pass it to the view to show them 
            if (postcodestring == "") //if the suburb is not searched then return all recycling centers
            {
                return View(db.RecyclingCentres.ToList());  //return all recycling centers to the model
            }
            else 
            {
                return View(db.RecyclingCentres.Where(x => x.Postcode == postcodestring).ToList());  //if the suburb is found then return 
                //nearby recycling centers
            }
          
           

        }


       //action to dispose
       protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Plaboo/Controllers/allCouncilPostcodesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Plaboo.Context;
using Plaboo.Models;

namespace Plaboo.Controllers
{
    public class allCouncilPostcodesController : Controller
    {
        private PlabooContext db = new PlabooContext();

        // GET: This is a GET http method to get all the allCouncilPostcodes
        public ActionResult Index()
        {
            return View(db.allCouncilPostcodes.ToList());
        }

       //to dispose off the object
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Plaboo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")



    <link href="~/Content/Images/favicon.ico" rel="shortcut icon" type="image/x-icon" />


    @* This is for the mapbox map. *@
    @*<script src='https://api.mapbox.com/mapbox-gl-js/v0.47.0/mapbox-gl.js'></script>
        <link href='https://api.mapbox.com/mapbox-gl-js/v0.47.0/mapbox-gl.css' rel='stylesheet' />*@
    <script src='https://api.tiles.mapbox.com/mapbox-gl-js/v1.8.0/mapbox-gl.js'></script>
    <link href='https://api.tiles.mapbox.com/mapbox-gl-js/v1.8.0/mapbox-gl.css' rel='stylesheet' />
    <script src='https://kit.fontawesome.com/a076d05399.js'></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    @*This is used for the Geocoding Mapbox API*@
    <script src='https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v2.2.0/mapbox-gl-geocoder.min.js'></script>
    <link rel='stylesheet' href='https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v2.2.0/mapbox-gl-geocoder.css' type='text/css' />

    <style>
        #homenav {
            color: black;
            font-family: 'Calibri';
            font-size: large;
        }

            #homenav:hover {
                background-color: ghostwhite;
            }

        .navbar-toggle {
            border-color: lightgreen;
        }


        .dropdown {
            position: relative;
        }

            .dropdown:hover .dropdown-menu {
                display: block;
            }

             footer {
            background-color: #DDE6EF;
            color: black;
        }
    </style>




</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top col-xs-12 col-sm-12 col-12">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span style="border-color:black;" class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <img onclick="location.href='@Url.Action("Index", "Home")'" src="~/Content/Images/plaboo2.png"
                     @*style="position:relative;top:-9px;width:55px;height:55px;">*@
                     style="position:relative;width:90px;height:auto;">

            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <!-- <li>@Html.ActionLink("Home", "Index", "Home")</li>-->


                    <li><a id="homenav" style="top:0px;" href="@Url.Action("Index", "Home")"><i class="fas fa-globe-asia"></i><span> Home</span></a></li>


                    <li class="dropdown">
                        <a id="homenav" style="top:0px;" href="#"><i class="fas fa-recycle"></i><span> Waste Management</span><span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a id="homenav" href="@Url.Action("Index", "allCouncilPostcodes")" class="dropdown-item"><span>Compare Suburbs</span></a></li>
                            <li><a id="homenav" href="@Url.Action("Index", "RecyclingCentres")" class="dropdown-item"><span>Suggestions</span></a></li>



                        </ul>
                    </li>
                    <li><a id="homenav" style="top:0px;" href="@Url.Action("Index", "Alternatives")"><i class="fas fa-directions"></i><span> Alternatives</span></a></li>
                    <li><a id="homenav" style="top:0px;" href="@Url.Action("Quiz", "Home")"><i class="fas fa-question-circle"></i><span> Quiz</span></a></li>



                </ul>

                @*@Html.Partial("_LoginPartial")*@
            </div>


        </div>

        <div class="header">

            <div class="progress-container">
                <div class="progress-bar" id="myBar"></div>
            </div>
        </div>
    </div>
   
    <div class="container-fluid body-content" style="">
        @RenderBody()



        <footer>
            <div class="container-fluid padding" style="margin-top:50px;">
                <div class="row text-center">
                    <div class="col-md-12">
                        <img style="width:140px;height:auto;" src="~/Content/Images/plaboo2.png" /> <h5>&copy; PlaBOO-2020 Developed by Team Slay</h5>
                    </div>
                </div>
            </div>
            @*<div id="footer">
            <div class="row">
                <div class="col-md-12">
                    <img style="width:1500px;height:400px;" src="~/Content/Images/footer.png" />
                </div>
            </div>

        </div>*@
            @*<div id="solution" style="background-color:black;margin-top:15px;">
            <div class="row">
                <div class="col-md-2"></div>
                <div class="col-md-1">
                    <img style="width:140px;height:120px;margin-top:20px;margin-bottom:20px;" src="~/Content/Images/plaboo.png" />
                </div>
                <div class="col-md-9">
                    <p style="font-family:'Calibri';color:white;margin-top:70px;">

                            Copyrights @@ All reserved. Plaboo-2020 Developed by Team Slay

                    </p>
                </div>


            </div>
        </div>*@

        </footer>
    </div>



    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>